name: Android Build Release Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: chmod +x ./gradlew ; ./gradlew build
      - name: Upload Release
        uses: actions/upload-artifact@v3
        with:
          name: app-release-unsigned
          path: ./app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Upload Debug
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: ./app/build/outputs/apk/debug/app-debug.apk
