name: Android Build Release Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: Configure Gradle
        run: chmod +x ./gradlew
      
      - name: Build Project
        run: ./gradlew assemble

      - name: build release
        run: ./gradlew assembleRelease
        
      - name: Prepare for Upload
        run: echo ${{ github.workspace}} ; mkdir -p ${{ github.workspace}} /app/build/outputs/apk/release/

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: ${{ github.workspace}} /app/build/outputs/apk/release/app-release.apk
